tool.conditionalProcessTool.config=Configure Conditional Process Tool
tool.conditionalProcessTool.delayBetweenExecution=Delay Between Execution
tool.conditionalProcessTool.delayBetweenExecution.desc=Introduce delay in second between each record.
tool.conditionalProcessTool.debugMode=Debug Mode
tool.conditionalProcessTool.condition=Condition
tool.conditionalProcessTool.condition.desc=Condition in Javascript. For example: "#form.demo.status#" == "Approved"
tool.conditionalProcessTool.tool=Process Tool